#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: jinbangyi/mongodb-web-ui
  # -- image tag
  tag: v0.0.1
  # -- image pull policy
  pullPolicy: IfNotPresent

controller:
  # -- Set the controller upgrade strategy
  strategy: Recreate

# -- environment variables.
# @default -- See [values.yaml](./values.yaml)
env: 
  WEBSOCKET_PORT:  8080
  # INIT_ASSETS: "0"

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

apisixRoute:
  serviceName: 'mongodb-web-ui'
  hosts: []
  plugins: []

configMaps:
  config:
    # -- Store homer configuration as a ConfigMap
    enabled: true
    # -- Homer configuration. [[ref]](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md)
    # @default -- See [values.yaml](./values.yaml)
    data:
      websocket.ts: |
        export const proxy = {
          secure: false,
          host: 'localhost',
          port: 8080,
        };
      mongodb.tsx: |
        const mongodbConnectionString='mongodb://localhost';
        export { mongodbConnectionString };
